name: Windows build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Build
        run: cmake